//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by jni4net. See http://jni4net.sourceforge.net/ 
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSchedule {
    
    
    #region Component Designer generated code 
    public partial class Game_ {
        
        public static global::java.lang.Class _class {
            get {
                return global::MSchedule.@__Game.staticClass;
            }
        }
    }
    #endregion
    
    #region Component Designer generated code 
    [global::net.sf.jni4net.attributes.JavaProxyAttribute(typeof(global::MSchedule.Game), typeof(global::MSchedule.Game_))]
    [global::net.sf.jni4net.attributes.ClrWrapperAttribute(typeof(global::MSchedule.Game), typeof(global::MSchedule.Game_))]
    internal sealed partial class @__Game : global::java.lang.Object {
        
        internal new static global::java.lang.Class staticClass;
        
        private @__Game(global::net.sf.jni4net.jni.JNIEnv @__env) : 
                base(@__env) {
        }
        
        private static void InitJNI(global::net.sf.jni4net.jni.JNIEnv @__env, java.lang.Class @__class) {
            global::MSchedule.@__Game.staticClass = @__class;
        }
        
        private static global::System.Collections.Generic.List<global::net.sf.jni4net.jni.JNINativeMethod> @__Init(global::net.sf.jni4net.jni.JNIEnv @__env, global::java.lang.Class @__class) {
            global::System.Type @__type = typeof(__Game);
            global::System.Collections.Generic.List<global::net.sf.jni4net.jni.JNINativeMethod> methods = new global::System.Collections.Generic.List<global::net.sf.jni4net.jni.JNINativeMethod>();
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "getgameNumber", "gameNumber0", "()I"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "getdate", "date1", "()Lsystem/DateTime;"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "getopponent", "opponent2", "()Ljava/lang/String;"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "getvenue", "venue3", "()Ljava/lang/String;"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "SetGameNumber", "SetGameNumber4", "(I)V"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "SetDate", "SetDate5", "(Lsystem/DateTime;)V"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "SetOpponent", "SetOpponent6", "(Ljava/lang/String;)V"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "SetVenue", "SetVenue7", "(Ljava/lang/String;)V"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "__ctorGame0", "__ctorGame0", "(Lnet/sf/jni4net/inj/IClrProxy;)V"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "__ctorGame1", "__ctorGame1", "(Lnet/sf/jni4net/inj/IClrProxy;ILsystem/DateTime;Ljava/lang/String;Ljava/lang/Str" +
                        "ing;)V"));
            return methods;
        }
        
        private static int gameNumber0(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()I
            // ()I
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            int @__return = default(int);
            try {
            global::MSchedule.Game @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::MSchedule.Game>(@__env, @__obj);
            @__return = ((int)(@__real.gameNumber));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static global::net.sf.jni4net.utils.JniHandle date1(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()Lsystem/DateTime;
            // ()LSystem/DateTime;
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::net.sf.jni4net.utils.JniHandle @__return = default(global::net.sf.jni4net.utils.JniHandle);
            try {
            global::MSchedule.Game @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::MSchedule.Game>(@__env, @__obj);
            @__return = global::net.sf.jni4net.utils.Convertor.StrongC2Jp<global::System.DateTime>(@__env, @__real.date);
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static global::net.sf.jni4net.utils.JniHandle opponent2(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()Ljava/lang/String;
            // ()LSystem/String;
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::net.sf.jni4net.utils.JniHandle @__return = default(global::net.sf.jni4net.utils.JniHandle);
            try {
            global::MSchedule.Game @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::MSchedule.Game>(@__env, @__obj);
            @__return = global::net.sf.jni4net.utils.Convertor.StrongC2JString(@__env, @__real.opponent);
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static global::net.sf.jni4net.utils.JniHandle venue3(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()Ljava/lang/String;
            // ()LSystem/String;
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::net.sf.jni4net.utils.JniHandle @__return = default(global::net.sf.jni4net.utils.JniHandle);
            try {
            global::MSchedule.Game @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::MSchedule.Game>(@__env, @__obj);
            @__return = global::net.sf.jni4net.utils.Convertor.StrongC2JString(@__env, @__real.venue);
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static void SetGameNumber4(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, int number) {
            // (I)V
            // (I)V
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            try {
            global::MSchedule.Game @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::MSchedule.Game>(@__env, @__obj);
            @__real.SetGameNumber(number);
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
        }
        
        private static void SetDate5(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, global::net.sf.jni4net.utils.JniLocalHandle date) {
            // (Lsystem/DateTime;)V
            // (LSystem/DateTime;)V
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            try {
            global::MSchedule.Game @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::MSchedule.Game>(@__env, @__obj);
            @__real.SetDate(global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::System.DateTime>(@__env, date));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
        }
        
        private static void SetOpponent6(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, global::net.sf.jni4net.utils.JniLocalHandle opp) {
            // (Ljava/lang/String;)V
            // (LSystem/String;)V
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            try {
            global::MSchedule.Game @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::MSchedule.Game>(@__env, @__obj);
            @__real.SetOpponent(global::net.sf.jni4net.utils.Convertor.StrongJ2CString(@__env, opp));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
        }
        
        private static void SetVenue7(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, global::net.sf.jni4net.utils.JniLocalHandle venue) {
            // (Ljava/lang/String;)V
            // (LSystem/String;)V
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            try {
            global::MSchedule.Game @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::MSchedule.Game>(@__env, @__obj);
            @__real.SetVenue(global::net.sf.jni4net.utils.Convertor.StrongJ2CString(@__env, venue));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
        }
        
        private static void @__ctorGame0(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__class, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()V
            // ()V
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            try {
            global::MSchedule.Game @__real = new global::MSchedule.Game();
            global::net.sf.jni4net.utils.Convertor.InitProxy(@__env, @__obj, @__real);
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
        }
        
        private static void @__ctorGame1(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__class, global::net.sf.jni4net.utils.JniLocalHandle @__obj, int number, global::net.sf.jni4net.utils.JniLocalHandle theDate, global::net.sf.jni4net.utils.JniLocalHandle opp, global::net.sf.jni4net.utils.JniLocalHandle theVenue) {
            // (ILsystem/DateTime;Ljava/lang/String;Ljava/lang/String;)V
            // (ILSystem/DateTime;LSystem/String;LSystem/String;)V
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            try {
            global::MSchedule.Game @__real = new global::MSchedule.Game(number, global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::System.DateTime>(@__env, theDate), global::net.sf.jni4net.utils.Convertor.StrongJ2CString(@__env, opp), global::net.sf.jni4net.utils.Convertor.StrongJ2CString(@__env, theVenue));
            global::net.sf.jni4net.utils.Convertor.InitProxy(@__env, @__obj, @__real);
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
        }
        
        new internal sealed class ContructionHelper : global::net.sf.jni4net.utils.IConstructionHelper {
            
            public global::net.sf.jni4net.jni.IJvmProxy CreateProxy(global::net.sf.jni4net.jni.JNIEnv @__env) {
                return new global::MSchedule.@__Game(@__env);
            }
        }
    }
    #endregion
}
