//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by jni4net. See http://jni4net.sourceforge.net/ 
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSchedule {
    
    
    #region Component Designer generated code 
    public partial class Schedule_ {
        
        public static global::java.lang.Class _class {
            get {
                return global::MSchedule.@__Schedule.staticClass;
            }
        }
    }
    #endregion
    
    #region Component Designer generated code 
    [global::net.sf.jni4net.attributes.JavaProxyAttribute(typeof(global::MSchedule.Schedule), typeof(global::MSchedule.Schedule_))]
    [global::net.sf.jni4net.attributes.ClrWrapperAttribute(typeof(global::MSchedule.Schedule), typeof(global::MSchedule.Schedule_))]
    internal sealed partial class @__Schedule : global::java.lang.Object {
        
        internal new static global::java.lang.Class staticClass;
        
        private @__Schedule(global::net.sf.jni4net.jni.JNIEnv @__env) : 
                base(@__env) {
        }
        
        private static void InitJNI(global::net.sf.jni4net.jni.JNIEnv @__env, java.lang.Class @__class) {
            global::MSchedule.@__Schedule.staticClass = @__class;
        }
        
        private static global::System.Collections.Generic.List<global::net.sf.jni4net.jni.JNINativeMethod> @__Init(global::net.sf.jni4net.jni.JNIEnv @__env, global::java.lang.Class @__class) {
            global::System.Type @__type = typeof(__Schedule);
            global::System.Collections.Generic.List<global::net.sf.jni4net.jni.JNINativeMethod> methods = new global::System.Collections.Generic.List<global::net.sf.jni4net.jni.JNINativeMethod>();
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "GetSchedule", "GetSchedule0", "()Lsystem/collections/IList;"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "GetHomeGames", "GetHomeGames1", "()Lsystem/collections/IList;"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "GetGameByNumber", "GetGameByNumber2", "(I)Lmschedule/Game;"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "AddToSchedule", "AddToSchedule3", "(Lmschedule/Game;)V"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "__ctorSchedule0", "__ctorSchedule0", "(Lnet/sf/jni4net/inj/IClrProxy;)V"));
            return methods;
        }
        
        private static global::net.sf.jni4net.utils.JniHandle GetSchedule0(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()Lsystem/collections/IList;
            // ()[[LSystem/Collections/Generic/IList`1;
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::net.sf.jni4net.utils.JniHandle @__return = default(global::net.sf.jni4net.utils.JniHandle);
            try {
            global::MSchedule.Schedule @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::MSchedule.Schedule>(@__env, @__obj);
            @__return = global::net.sf.jni4net.utils.Convertor.FullC2J<global::System.Collections.Generic.IList<MSchedule.Game>>(@__env, @__real.GetSchedule());
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static global::net.sf.jni4net.utils.JniHandle GetHomeGames1(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()Lsystem/collections/IList;
            // ()LSystem/Collections/IList;
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::net.sf.jni4net.utils.JniHandle @__return = default(global::net.sf.jni4net.utils.JniHandle);
            try {
            global::MSchedule.Schedule @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::MSchedule.Schedule>(@__env, @__obj);
            @__return = global::net.sf.jni4net.utils.Convertor.FullC2J<global::System.Collections.IList>(@__env, @__real.GetHomeGames());
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static global::net.sf.jni4net.utils.JniHandle GetGameByNumber2(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, int number) {
            // (I)Lmschedule/Game;
            // (I)LMSchedule/Game;
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::net.sf.jni4net.utils.JniHandle @__return = default(global::net.sf.jni4net.utils.JniHandle);
            try {
            global::MSchedule.Schedule @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::MSchedule.Schedule>(@__env, @__obj);
            @__return = global::net.sf.jni4net.utils.Convertor.StrongC2Jp<global::MSchedule.Game>(@__env, @__real.GetGameByNumber(number));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static void AddToSchedule3(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, global::net.sf.jni4net.utils.JniLocalHandle game) {
            // (Lmschedule/Game;)V
            // (LMSchedule/Game;)V
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            try {
            global::MSchedule.Schedule @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::MSchedule.Schedule>(@__env, @__obj);
            @__real.AddToSchedule(global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::MSchedule.Game>(@__env, game));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
        }
        
        private static void @__ctorSchedule0(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__class, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()V
            // ()V
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            try {
            global::MSchedule.Schedule @__real = new global::MSchedule.Schedule();
            global::net.sf.jni4net.utils.Convertor.InitProxy(@__env, @__obj, @__real);
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
        }
        
        new internal sealed class ContructionHelper : global::net.sf.jni4net.utils.IConstructionHelper {
            
            public global::net.sf.jni4net.jni.IJvmProxy CreateProxy(global::net.sf.jni4net.jni.JNIEnv @__env) {
                return new global::MSchedule.@__Schedule(@__env);
            }
        }
    }
    #endregion
}
