// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by jni4net. See http://jni4net.sourceforge.net/ 
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

package mschedule;

@net.sf.jni4net.attributes.ClrType
public class Game extends system.Object {
    
    //<generated-proxy>
    private static system.Type staticType;
    
    protected Game(net.sf.jni4net.inj.INJEnv __env, long __handle) {
            super(__env, __handle);
    }
    
    @net.sf.jni4net.attributes.ClrConstructor("()V")
    public Game() {
            super(((net.sf.jni4net.inj.INJEnv)(null)), 0);
        mschedule.Game.__ctorGame0(this);
    }
    
    @net.sf.jni4net.attributes.ClrConstructor("(ILSystem/DateTime;LSystem/String;LSystem/String;)V")
    public Game(int number, system.DateTime theDate, java.lang.String opp, java.lang.String theVenue) {
            super(((net.sf.jni4net.inj.INJEnv)(null)), 0);
        mschedule.Game.__ctorGame1(this, number, theDate, opp, theVenue);
    }
    
    @net.sf.jni4net.attributes.ClrMethod("()V")
    private native static void __ctorGame0(net.sf.jni4net.inj.IClrProxy thiz);
    
    @net.sf.jni4net.attributes.ClrMethod("(ILsystem/DateTime;Ljava/lang/String;Ljava/lang/String;)V")
    private native static void __ctorGame1(net.sf.jni4net.inj.IClrProxy thiz, int number, system.DateTime theDate, java.lang.String opp, java.lang.String theVenue);
    
    @net.sf.jni4net.attributes.ClrMethod("()I")
    public native int getgameNumber();
    
    @net.sf.jni4net.attributes.ClrMethod("()LSystem/DateTime;")
    public native system.DateTime getdate();
    
    @net.sf.jni4net.attributes.ClrMethod("()LSystem/String;")
    public native java.lang.String getopponent();
    
    @net.sf.jni4net.attributes.ClrMethod("()LSystem/String;")
    public native java.lang.String getvenue();
    
    @net.sf.jni4net.attributes.ClrMethod("(I)V")
    public native void SetGameNumber(int number);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/DateTime;)V")
    public native void SetDate(system.DateTime date);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/String;)V")
    public native void SetOpponent(java.lang.String opp);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/String;)V")
    public native void SetVenue(java.lang.String venue);
    
    public static system.Type typeof() {
        return mschedule.Game.staticType;
    }
    
    private static void InitJNI(net.sf.jni4net.inj.INJEnv env, system.Type staticType) {
        mschedule.Game.staticType = staticType;
    }
    //</generated-proxy>
}
