// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by jni4net. See http://jni4net.sourceforge.net/ 
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

package mschedule;

@net.sf.jni4net.attributes.ClrType
public class Schedule extends system.Object {
    
    //<generated-proxy>
    private static system.Type staticType;
    
    protected Schedule(net.sf.jni4net.inj.INJEnv __env, long __handle) {
            super(__env, __handle);
    }
    
    @net.sf.jni4net.attributes.ClrConstructor("()V")
    public Schedule() {
            super(((net.sf.jni4net.inj.INJEnv)(null)), 0);
        mschedule.Schedule.__ctorSchedule0(this);
    }
    
    @net.sf.jni4net.attributes.ClrMethod("()V")
    private native static void __ctorSchedule0(net.sf.jni4net.inj.IClrProxy thiz);
    
    @net.sf.jni4net.attributes.ClrMethod("()[[LSystem/Collections/Generic/IList`1;")
    public native system.collections.IList GetSchedule();
    
    @net.sf.jni4net.attributes.ClrMethod("()LSystem/Collections/IList;")
    public native system.collections.IList GetHomeGames();
    
    @net.sf.jni4net.attributes.ClrMethod("(I)LMSchedule/Game;")
    public native mschedule.Game GetGameByNumber(int number);
    
    @net.sf.jni4net.attributes.ClrMethod("(LMSchedule/Game;)V")
    public native void AddToSchedule(mschedule.Game game);
    
    public static system.Type typeof() {
        return mschedule.Schedule.staticType;
    }
    
    private static void InitJNI(net.sf.jni4net.inj.INJEnv env, system.Type staticType) {
        mschedule.Schedule.staticType = staticType;
    }
    //</generated-proxy>
}
